cached_user_env: {}
context:
  active_environment: local-mcsp
environments:
  local:
    wxo_url: http://localhost:4321
  local-mcsp:
    auth_type: mcsp
    wxo_url: https://api.dl.watson-orchestrate.ibm.com/instances/20260316-2127-2613-70e8-3841b0fdd530
python_registry:
  skip_version_check: false
  test_package_version_override: null
  type: pypi
